version: '3.7'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  crud_service:
    build:
      context: ./crud_service
    environment:
      DB_HOST: db
    depends_on:
      - db
    ports:
      - "8001:8001"

  api_gateway:
    build:
      context: ./api_gateway
    depends_on:
      - crud_service
    ports:
      - "8000:8000"

  image_service:
    build:
      context: ./image_service
    depends_on:
      - mongo
    ports:
      - "8002:8002"

volumes:
  db_data:
  mongo_data:
